import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LogoutButton from "../components/LogoutButton";
import Link from "next/link";
import { AuthProvider } from "../utils/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <div className="flex justify-between p-4">
            <Link href="/" className="text-blue-500 hover:text-blue-700 underline">
              Home
            </Link>
            <LogoutButton />
          </div>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
